### ISSUE TITLE
Strange certfp generation instructions

### ISSUE THREAD

**Issue by Mikaela** [freenode/www#6]
> If you do not want to protect your certificate with a passphrase, add -nodes to the options below. Not having a passphrase means anybody with access to read your certificate file will be able to identify as you. With a passphrase, both access to the certificate file and knowledge of the passphrase would be required.

Most of clients don't understand password protected certificates.

> `openssl req -newkey rsa:2048 -days 730 -x509 -keyout mynick.key -out mynick.cert`

Why are so many files generated?

There are multiple details asked while they aren't needed and asking them is useless.

> cat mynick.cert mynick.key > mynick.pem

Why this was not done directly?

> rm mynick.cert mynick.key

if those files are removed anyway.

* * * * *

Usually the certificate is created using

```
openssl req -nodes -newkey rsa:4096 -keyout MYNICK.pem -x509 -days 3650 -out MYNICK.pem -subj "/CN=MYNICK"
```

which doesn't ask any questions.

**Comment by prgmrbill** [comment]
I followed the steps on the website (https://freenode.net/certfp), and I ended up with this error:

gnutls: invalid certificate "/home/user/cert-test/ssl/my-freenode-nick.pem", error: ASN1 parser: Error in TAG.

I'm using Weechat 1.1.1

Here's how I got it working:
- remove old .pem
- run the above command  suggested by @Mikaela to generate a new one
- update fingerprint with nickserv and in your client
- reconnect

Using that, I was able to successfully authenticate using my fingerprint.

**Comment by Mikaela** [comment]
Oh and it should probably also be noticed that usually getting fingerprint seems to happen with `openssl x509 -sha1 -noout -fingerprint -in MYNICK.pem | tr -d ':' | tr 'A-Z' 'a-z'` instead of `openssl x509 -sha1 -noout -fingerprint -in mynick.pem | sed -e 's/^.*=//;s/://g;y/ABCDEF/abcdef/' `

**Comment by maxteufel** [comment]
It is also possible to generate ECDSA certificates, using (where `${curve}` can be any curve supported by openssl (`openssl ecparam -list_curves`) but clients using gnutls (WeeChat) don't support everything listed there (`prime256v1` and `secp521r1` should work)):

```bash
openssl ecparam -genkey -name ${curve} -out temp-ecdsa-key.pem
openssl req -nodes -sha256 -newkey ec:temp-ecdsa-key.pem -keyout ${nick}.pem -x509 -days ${days} -out ${nick}.pem -subj "/CN=${nick}"
```

Then remove the `temp-ecdsa-key.pem` file, it's only used for curve parameters in the second step.

**Comment by kjayne** [comment]
> Most of clients don't understand password protected certificates.

Some clients do, and those that don't should learn to do so, or the cert is effectively no better than just leaving the password stored in a file.

> Why are so many files generated?

The openssl I used to test these would not write the cert and key to the same file.

> getting fingerprint seems to happen with

There's not much difference between using sed and using tr. The given sed recipe will strip the leading text.

> It is also possible to generate ECDSA certificates

This is a good idea after the landscape settles down a little bit on ECDSA support and which curves are widely-implemented.

@prgmrbill: I'd like to know why the instructions didn't work for you. We could add `-batch` to the options to avoid the questions, but that shouldn't have any syntactic effect on the output. Can you share the my-freenode-nick.pem file you generated?

**Comment by Mikaela** [comment]
> Some clients do, and those that don't should learn to do so, or the cert is effectively no better than just leaving the password stored in a file.

Having password protected certificate sounds strange with irssi/weechat in screen or some bouncer as those would probably have to store the password in plain text.

**Comment by Mikaela** [comment]
The new site didn't even have certfp last time I checked so I am closing this.
